# Generated by Django 5.0.6 on 2024-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0009_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(default="1234567890", max_length=15),
        ),
    ]
