# Generated by Django 5.0.6 on 2024-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0011_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="mobile",
            field=models.CharField(default=9876543210, max_length=15),
        ),
    ]
