# Generated by Django 5.0.6 on 2024-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0012_students_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
