# Generated by Django 5.0.6 on 2024-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0013_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("role", models.CharField(max_length=15)),
            ],
        ),
    ]
